# Markdownlint configuration file
default: true
line-length: false
no-duplicate-heading:
    siblings_only: true
no-inline-html:
    allowed_elements:
        - img
        - p
        - kbd
        - details
        - summary
MD056: false
MD038: false
